export const API_CONFIG = {
  VERSION: 'v1',
  BASE_URL: 'http://192.168.29.84:3000/api',
  CLIENT_TYPE: 'mobile',
  TIMEOUT: 30000,
};

export const QR_CONFIG = {
  APP_NAME: 'Nirbhaya - Women Safety',
  APP_PLAY_STORE_URL: 'https://play.google.com/store/apps/details?id=com.nirbhaya.womensafety',
  PUBLIC_SCAN_URL: 'https://qr.nirbhaya.app/scan',
};

export const ENDPOINTS = {
  auth: {
    login: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/login`,
    register: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/register`,
    logout: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/logout`,
    refreshToken: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/refresh-token`,
    biometricLogin: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/biometric-login`,
    changePassword: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/change-password`,
    forgotPassword: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/forgot-password`,
    resetPassword: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/reset-password`,
    forceLogout: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/auth/force-logout/${userId}`,
  },
  users: {
    profile: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}`,
    updateProfile: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}`,
    role: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/role`,
    emergencyContactsAll: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/emergency-contacts/all`,
    emergencyContactsDefault: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/emergency-contacts/default`,
    emergencyContactsAllWithSupport: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/emergency-contacts/all-with-support`,
    preferences: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/emergency-contacts/preferences`,
    updatePreferences: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/emergency-contacts/preferences`,
    emergencyContacts: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/emergency-contacts`,
    addEmergencyContact: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/emergency-contacts`,
    updateEmergencyContact: (id, contactId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/emergency-contacts/${contactId}`,
    deleteEmergencyContact: (id, contactId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/emergency-contacts/${contactId}`,
    locations: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/locations`,
    saveLocation: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/locations`,
    sosAlerts: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/sos-alerts`,
    notifications: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/notifications`,
    markNotificationRead: (userId, notificationId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${userId}/notifications/${notificationId}/read`,
    children: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/children`,
    addChild: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/children`,
    settings: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/settings`,
    updateSettings: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/users/${id}/settings`,
  },
  sos: {
    trigger: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/trigger`,
    active: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/active`,
    history: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/history`,
    resolve: (alertId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/${alertId}/resolve`,
    delete: (alertId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/${alertId}`,
    locationUpdate: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sos/location-update`,
  },
  families: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families`,
    create: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families`,
    details: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}`,
    update: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}`,
    delete: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}`,
    members: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/members`,
    addMember: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/members`,
    removeMember: (familyId, userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/members/${userId}`,
    updateMemberRole: (familyId, userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/members/${userId}/role`,
    relationships: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/relationships`,
    addRelationship: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/relationships`,
    deleteRelationship: (familyId, id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/relationships/${id}`,
    userLookup: (email) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/users/lookup/${email}`,
    locations: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/locations`,
    memberLocation: (familyId, userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/families/${familyId}/members/${userId}/location`,
  },
  familyPlaces: {
    create: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places`,
    list: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places`,
    update: (familyId, placeId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places/${placeId}`,
    delete: (familyId, placeId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places/${placeId}`,
    check: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places/check`,
    nearest: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/family-places/${familyId}/places/nearest`,
  },
  childcare: {
    tips: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/tips`,
    tip: (tipId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/tips/${tipId}`,
    addFavorite: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/tips/favorites`,
    removeFavorite: (tipId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/tips/favorites/${tipId}`,
    categories: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/categories`,
    chatMessages: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/chat/messages`,
    sendChatMessage: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/chat/messages`,
    conversations: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/chat/conversations`,
    deleteConversation: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/chat/conversations/${id}`,
    children: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/children`,
    addChild: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/children`,
    updateChild: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/children/${childId}`,
    deleteChild: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/children/${childId}`,
    growthTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/growth/${childId}`,
    addGrowthTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/growth/${childId}`,
    feedingTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/feeding/${childId}`,
    addFeedingTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/feeding/${childId}`,
    sleepTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/sleep/${childId}`,
    addSleepTracker: (childId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/childcare/trackers/sleep/${childId}`,
  },
  events: {
    addLocation: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/location`,
    addBatchLocations: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/locations/batch`,
    suggestions: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/suggestions`,
    respondSuggestion: (suggestionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/suggestions/${suggestionId}/respond`,
    activityLogs: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/activity-logs`,
    addActivityLog: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/activity-logs`,
    context: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/events/families/${familyId}/context`,
  },
  behavior: {
    analyze: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/analyze`,
    anomalies: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/anomalies`,
    summary: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/summary/${userId}`,
    feedback: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/feedback`,
    settings: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/settings/${userId}`,
    updateSettings: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/settings/${userId}`,
    routines: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/routines/${userId}`,
    learnRoutine: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/routines/learn`,
    alerts: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/alerts/${userId}`,
    resolveAlert: (alertId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/behavior/alerts/${alertId}/resolve`,
  },
  settings: {
    groqKey: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/settings/groq-key`,
  },
  consent: {
    get: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/consent/consent-settings`,
    update: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/consent/consent-settings`,
    updateCategories: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/consent/categories`,
    auditLogs: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/consent/audit-logs`,
  },
  theme: {
    current: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/themes/current`,
    all: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/themes`,
    preference: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/themes/preference`,
    setUser: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/themes/user`,
    config: (themeId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/themes/${themeId}/config`,
  },
  menu: {
    user: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/menus/user`,
    all: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/menus`,
    byId: (menuId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/menus/${menuId}`,
  },
  permissions: {
    current: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/permissions/current`,
    byRole: (role) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/permissions/role/${role}`,
    updateUser: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/permissions/user`,
  },
  safetyTutorials: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials`,
    byId: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials/${id}`,
    categories: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials/categories`,
    search: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials/search`,
    byCategory: (categoryId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials/category/${categoryId}`,
    byDifficulty: (difficulty) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-tutorials/difficulty/${difficulty}`,
  },
  safetyNews: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news`,
    byId: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/${id}`,
    featured: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/featured`,
    categories: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/categories`,
    search: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/search`,
    byCategory: (categoryId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/category/${categoryId}`,
    latest: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/latest`,
    popular: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-news/popular`,
  },
  safetyLaws: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws`,
    byId: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/${id}`,
    categories: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/categories`,
    jurisdictions: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/jurisdictions`,
    search: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/search`,
    byCategory: (categoryId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/category/${categoryId}`,
    byJurisdiction: (jurisdictionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/jurisdiction/${jurisdictionId}`,
    recent: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safety-laws/recent`,
  },
  grievance: {
    submit: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance`,
    myList: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance/my`,
    details: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance/${id}`,
    detailsWithMessages: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance/${id}/details`,
    update: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance/${id}`,
    messages: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/grievance/${id}/messages`,
  },
  sessions: {
    history: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/sessions/history`,
  },
  homeAutomation: {
    devices: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices`,
    device: (deviceId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices/${deviceId}`,
    control: (deviceId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices/${deviceId}/control`,
    add: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices`,
    update: (deviceId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices/${deviceId}`,
    delete: (deviceId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/home-automation/devices/${deviceId}`,
  },
  liveStream: {
    start: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/start`,
    session: (sessionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/session/${sessionId}`,
    updateStream: (sessionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/session/${sessionId}/stream`,
    updateLocation: (sessionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/session/${sessionId}/location`,
    stop: (sessionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/session/${sessionId}/stop`,
    active: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/active/${userId}`,
    history: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/history/${userId}`,
    addViewer: (sessionId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/live-stream/session/${sessionId}/view`,
  },
  qr: {
    myCodes: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/my-codes`,
    permissions: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/permissions`,
    accessHistory: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/access-history`,
    generate: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/generate`,
    revoke: (tokenId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/revoke/${tokenId}`,
    scan: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/qr/scan`,
  },
  cylinder: {
    history: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/cylinder/history`,
    save: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/cylinder/save`,
    verify: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/cylinder/verify`,
    delete: (id) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/cylinder/${id}`,
  },
  safeRoute: {
    analyze: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safe-route/analyze`,
    history: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safe-route/history`,
    save: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safe-route/save`,
    stats: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safe-route/stats`,
    hotspots: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/safe-route/hotspots`,
  },
  banners: {
    list: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/banners`,
  },
  admin: {
    dashboard: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/dashboard`,
    users: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users`,
    userDetail: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}`,
    updateUserRole: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}/role`,
    updateUserStatus: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}/status`,
    deleteUser: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}`,
    searchUsers: (query) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/search?q=${query}`,
    families: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/families`,
    familyDetail: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/families/${familyId}`,
    updateFamily: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/families/${familyId}`,
    deleteFamily: (familyId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/families/${familyId}`,
    sosAlerts: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/sos-alerts`,
    sosAlertDetail: (alertId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/sos-alerts/${alertId}`,
    resolveSOSAlert: (alertId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/sos-alerts/${alertId}/resolve`,
    activeLocations: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/locations/active`,
    userLocationHistory: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/locations/user/${userId}`,
    emergencyContacts: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/emergency-contacts`,
    grievances: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/grievances`,
    updateGrievanceStatus: (grievanceId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/grievances/${grievanceId}/status`,
    activityLogs: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/activity-logs`,
    systemHealth: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/system/health`,
    forceLogoutUser: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}/force-logout`,
    sendNotification: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/notifications/${userId}`,
    broadcastNotification: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/notifications/broadcast`,
    notifications: `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/notifications`,
    userDependents: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}/dependents`,
    userFamilyMembers: (userId) => `${API_CONFIG.BASE_URL}/${API_CONFIG.VERSION}/mobile/admin/users/${userId}/family-members`,
  },
};

export default ENDPOINTS;
